#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: 3d985eb
#
# Source0 file verified with key 0x4A77747BC2386E50 (digikamdeveloper@gmail.com)
#
Name     : digikam
Version  : 8.3.0
Release  : 71
URL      : https://download.kde.org/stable/digikam/8.3.0/digiKam-8.3.0.tar.xz
Source0  : https://download.kde.org/stable/digikam/8.3.0/digiKam-8.3.0.tar.xz
Source1  : https://download.kde.org/stable/digikam/8.3.0/digiKam-8.3.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC0-1.0 CDDL-1.0 CECILL-1.1 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT
BuildRequires : ImageMagick
BuildRequires : akonadi-contacts-dev
BuildRequires : bison-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : cmake
BuildRequires : doxygen
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : exiv2-dev
BuildRequires : expat-dev
BuildRequires : extra-cmake-modules pkgconfig(glib-2.0)
BuildRequires : extra-cmake-modules-data
BuildRequires : flex
BuildRequires : gettext-dev
BuildRequires : glibc-dev
BuildRequires : kcalendarcore-dev
BuildRequires : kcodecs-dev
BuildRequires : kcompletion-dev
BuildRequires : kfilemetadata-dev
BuildRequires : kiconthemes-dev
BuildRequires : kio-dev
BuildRequires : knotifications-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kwindowsystem-dev
BuildRequires : kxmlgui-dev
BuildRequires : lensfun-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libksane-dev
BuildRequires : libpng-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-dev
BuildRequires : marble-dev
BuildRequires : mesa-dev
BuildRequires : opencv-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(lensfun)
BuildRequires : pkgconfig(libavfilter)
BuildRequires : pkgconfig(libavutil)
BuildRequires : pkgconfig(libgphoto2)
BuildRequires : pkgconfig(libswscale)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libva-wayland)
BuildRequires : pkgconfig(libva-x11)
BuildRequires : pkgconfig(vdpau)
BuildRequires : qt6base-dev
BuildRequires : qt6webengine-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtkeychain-dev
BuildRequires : qtscript-dev
BuildRequires : qtwebengine-dev
BuildRequires : solid-dev
BuildRequires : threadweaver-dev
BuildRequires : tiff-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
------------------------------------------------------------------------------
1. NAMING CONVENTIONS FOR SYNTAX HIGHLIGHTING
------------------------------------------------------------------------------

%prep
%setup -q -n digikam-8.3.0
cd %{_builddir}/digikam-8.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710527156
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DENABLE_QWEBENGINE=TRUE \
-DBUILD_TESTING=OFF
make  %{?_smp_mflags}  -w
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DENABLE_QWEBENGINE=TRUE \
-DBUILD_TESTING=OFF
make  %{?_smp_mflags}  -w
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710527156
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/digikam
cp %{_builddir}/digikam-%{version}/COPYING %{buildroot}/usr/share/package-licenses/digikam/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/digikam-%{version}/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/digikam/be561fe6eb626c2566b9a6c0885554b4ee4e6b74 || :
cp %{_builddir}/digikam-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/digikam/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/digikam-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/digikam/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/digikam-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/digikam/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/digikam-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/digikam/e3bdbf20d43fc066a1b40a64d57d4ae5a31f177f || :
cp %{_builddir}/digikam-%{version}/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/digikam/e3bdbf20d43fc066a1b40a64d57d4ae5a31f177f || :
cp %{_builddir}/digikam-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/digikam/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/digikam-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/digikam/fa05e58320cb7c64786b26396f4b992579a628bc || :
cp %{_builddir}/digikam-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/digikam/fa05e58320cb7c64786b26396f4b992579a628bc || :
cp %{_builddir}/digikam-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/digikam/0b71159e19bef95069e18d17296291916e89b5cd || :
cp %{_builddir}/digikam-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/digikam/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/digikam-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/digikam/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/digikam-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/digikam/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/digikam-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/digikam/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/digikam-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/digikam/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3 || :
cp %{_builddir}/digikam-%{version}/core/dplugins/generic/tools/mediaserver/upnpsdk/Platinum/LICENSE.txt %{buildroot}/usr/share/package-licenses/digikam/a5bbd41410f38b2dd525e6c601f29b1736db13f9 || :
cp %{_builddir}/digikam-%{version}/core/libs/dimg/filters/greycstoration/cimg/LICENSE.txt %{buildroot}/usr/share/package-licenses/digikam/2da2357c9706c1416e5d65e4a2e21a1c77fc9dff || :
cp %{_builddir}/digikam-%{version}/core/libs/dngwriter/extra/COPYING-ADOBE-XMPSDK %{buildroot}/usr/share/package-licenses/digikam/b2245a16f088ed2b57e39c6f3a92b0883c0b062f || :
cp %{_builddir}/digikam-%{version}/core/libs/dplugins/webservices/o2/LICENSE %{buildroot}/usr/share/package-licenses/digikam/d1199253fd73ffa134ea99cd70609a908c3bc5b9 || :
cp %{_builddir}/digikam-%{version}/core/libs/rawengine/libraw/COPYRIGHT %{buildroot}/usr/share/package-licenses/digikam/e86ca32ed57e181b74fd60bbb8301acf014a9a6c || :
cp %{_builddir}/digikam-%{version}/core/libs/rawengine/libraw/LICENSE.CDDL %{buildroot}/usr/share/package-licenses/digikam/c24b9c7ef03687bf0141f85a1b7ed81459944c3c || :
cp %{_builddir}/digikam-%{version}/core/libs/rawengine/libraw/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/digikam/39a21f33cadea18adcc23bf808d7d5ea6419c8b1 || :
cp %{_builddir}/digikam-%{version}/core/libs/video/QtAVPlayer/LICENSE %{buildroot}/usr/share/package-licenses/digikam/a774db7c7e3a56322c933b6c8e50addf34fd929a || :
cp %{_builddir}/digikam-%{version}/project/bundles/homebrew/installer/GPL.txt %{buildroot}/usr/share/package-licenses/digikam/075bb44a94e785a073154a32aa32554587f330f2 || :
cp %{_builddir}/digikam-%{version}/project/bundles/macports/installer/GPL.txt %{buildroot}/usr/share/package-licenses/digikam/075bb44a94e785a073154a32aa32554587f330f2 || :
cp %{_builddir}/digikam-%{version}/project/bundles/mxe/installer/GPL.txt %{buildroot}/usr/share/package-licenses/digikam/ef250cb30fe89ea6687a0fe04fd552dbdc93e0e0 || :
cp %{_builddir}/digikam-%{version}/project/bundles/vcpkg/installer/GPL.txt %{buildroot}/usr/share/package-licenses/digikam/ef250cb30fe89ea6687a0fe04fd552dbdc93e0e0 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
